module arduinocore {
    requires commons.compress;
    requires apple;
    requires bcprov.jdk15on;
    requires commons.codec;
    requires commons.exec;
    requires commons.lang3;
    requires commons.logging;
    requires commons.net;
    requires com.fasterxml.jackson.annotation;
    requires com.fasterxml.jackson.core;
    requires com.fasterxml.jackson.databind;
    requires bcpg.jdk15on;
    requires com.fasterxml.jackson.module.mrbean;
    requires java.semver;
    requires jmdns;
    requires jna;
    // requires jna.platform;
    requires jsch;
    requires jssc;
    requires slf4j.api;
    requires slf4j.simple;
    requires java.desktop;
    requires java.logging;
    requires java.scripting;
    // requires java.base;

    exports processing.app.helpers to app, test;
    exports processing.app to app, test;
    exports cc.arduino to app, test;
    exports cc.arduino.packages to app, test;
    exports cc.arduino.packages.uploaders to app, test;
    exports processing.app.debug to app, test;
    exports processing.app.legacy to app;
    exports cc.arduino.contributions to app, test;
    exports cc.arduino.contributions.libraries to app, test;
    exports cc.arduino.contributions.packages to app, test;
    exports cc.arduino.files to app, test;
    exports processing.app.helpers.filefilters to app;
    exports processing.app.packages to app, test;
    exports cc.arduino.packages.ssh to app;
    exports cc.arduino.i18n to app, test;
    exports cc.arduino.utils to app, test;
    exports processing.app.macosx to app, test;
    exports processing.app.windows to app, test;
    exports processing.app.linux to app, test;
    exports cc.arduino.net to app, test;
}
